### PR TITLE
add Ridder method; close #281

### LINKED ISSUE #281: [FR] Implement Ridder's method
I would love to see [Ridder's method](https://en.wikipedia.org/wiki/Ridders%27_method) implemented ^_^

### PR DESCRIPTION
**Pull request by jverzani**
This adds a `Ridder` method to the mix of accelerated bracketing methods.

### CODE REVIEW

**Comment by KronosTheLate** [comment]
A note - i know that wikipedia says that the order of convergense is 2/sqrt(2). But my teacher claims that it is in fact 3/sqrt(3). When i confronted him with that discrepancy, he maintained the 3/sqrt(3) claim, saying that he knows some people claim it is 2/sqrt(2), but that Ridder proved in his original (quite short) paper that it is in fact 3/sqrt(3). I have not found time to investigate this.

**Comment by KronosTheLate** [comment]
The slahes in the previous comment mean or, not division

**Comment by jverzani** [comment]
Typically, the rate of convergence raised to the number of function evaluations is used for this measure. So, if it converges quadratically, you get 2^(1/2). I didn't look up the paper though, will have to do so if I can find it.

**Comment by jverzani** [comment]
Okay, the error looks like e_3 = C e_0 * e_1 * e_2 (https://cs.fit.edu/~dmitra/SciComp/Resources/RidderMethod.pdf), which suggests e_{n+1} ~ e_n^(1.83...) giving convergence between  quadratic (e.g.. Newton) and the secant (~1.6). This would translated into typically fewer iterations to convergence than the secant method, but with two function evaluations it would be expected to run a bit slower than other algorithms. Here is some early benchmarking with `f(x,p) = cos(x) - x/p; x0 = (0, pi/2)`:

```
julia> @btime solve(ZeroProblem($f,$x0), Roots.AlefeldPotraShi(), p=p) setup=(p=rand(2:5));
  662.879 ns (0 allocations: 0 bytes)

julia> @btime solve(ZeroProblem($f,$x0), Roots.Ridders(), p=p) setup=(p=rand(2:5));
  740.583 ns (0 allocations: 0 bytes)

julia> @btime solve(ZeroProblem($f,$x0), Roots.ITP(), p=p) setup=(p=rand(2:5));
  871.077 ns (0 allocations: 0 bytes)

julia> @btime solve(ZeroProblem($f,$x0), Roots.Secant(), p=p) setup=(p=rand(2:5));
  255.037 ns (0 allocations: 0 bytes)
```

**Pull request merged**
