### PR TITLE
Updates for Julia 0.6

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by jverzani** [comment]
Thanks! I was thinking of doing two things when v0.6 is released: update for changes to syntax, but also moving the special support for polynomials into a different package. I have a PR that I've been pushing changes to for that move that includes some of this. I'll borrow your changes for that other package. Will merge this once I figure out why the tests are having issues.

**Comment by jverzani** [comment]
I think the `newton` constructor is an issue with v0.6, atleast this was fixed in my `nopolys` branch. I'll have to sort this out.

**Comment by jverzani** [comment]
Thanks @ararslan !

**Comment by ararslan** [comment]
And thank you for finishing the job! :)

**Pull request merged**
