### PR TITLE
Make find roots find more roots w/ complex allowed

### PR DESCRIPTION
**Pull request by djsegal**
Made in favor of changes from:

+ https://github.com/JuliaMath/Roots.jl/pull/108

**update:** guessing the failed jobs on windows are from that convert magic you did before. don't have a way to test this though

------

Also, it took **1395** calls to solve the following root equation:

```
    f7 = CallableFunction(x -> sin(x-0.1), 0)
    rts = find_zeros(f7, -pi/2, pi/2)
    println(f7.n)
    @test f7.n <= 6000 # 3002
```

### CODE REVIEW

**Comment by djsegal** [comment]
Doesn't work for crazy nonlinear functions (i.e. the fussy ones from the test suite).

One way I thought about combatting that was to check the smallest value in `f.(cur_range)`. 

A la,

```julia
    if isempty(root_list) && no_pts > 2
      log_values = map(abs, cur_values)
      log_values = map(log10, log_values)

      cur_low_bar = maximum(log_values) / 10

      log_values[1] = Inf
      log_values[end] = Inf

      cur_indices = collect(1:length(log_values))
      sort!(cur_indices, by= cur_index -> abs(log_values[cur_index]) )

      for cur_index in cur_indices[1:min(4, length(cur_indices))]
        log_value = log_values[cur_index]

        ( log_value < cur_low_bar ) || break

        tmp_roots = find_bisection_roots(f, collect(linspace(cur_range[cur_index-1], cur_range[cur_index+1], Int(ceil(no_pts/2)))), abstol, reltol)
        isempty(tmp_roots) && continue

        append!(root_list, tmp_roots)
        break
      end
    end
```

It just seemed kind of futile to get a zero value so close to one that equals something like `10^126`

**Comment by djsegal** [comment]
@jverzani sorry for flooding you, but I think this algorithm is pretty down pat now.

Works on complex numbers and it's fast with relatively few calls :)

**Comment by jverzani** [comment]
Yes, I benchmarked with the current `find_zeros` PR I have. The two are close in performance, with yours being a bit faster with the given defaults, but I think mine is a bit more transparent and the tolerances easier to adjust for the algorithm. As both will fail on problematic problems (all will, of course), having adjustments that are easier to understand can be helpful. 

As for the issue with functions going slightly complex that you have, it seems better to do this with a wrapper (making it opt in). Something like this seems to work:

```

mutable struct Trim
f
end
(F::Trim)(x) = begin
    cur_f = float(F.f(x))
    isreal(cur_f) && return cur_f
    real_f, imag_f = real(cur_f), imag(cur_f)
    cur_ratio = abs( real_f / imag_f )
    real_f = isapprox(real_f, 0.0, atol=abstol) ? 0.0 : real_f
    ( cur_ratio > 1e6 ) && return real_f
    ( abs(real_f) < 1e-3 && abs(imag_f) < 1e-3 ) && return real_f
    cur_f
end

# an example of it working
find_zeros(Trim(sin), -1/2, 1)
```

**Comment by djsegal** [comment]
@jverzani are you looking at the first commit or the whole PR?

I changed the complex treatment to just:

+ work_f(x) = real(float(f(complex(x))))

The whole PR is also much faster than the first commit

**Comment by jverzani** [comment]
Let me check, I thought I had pulled in the latest, but looks like I haven't.

**Comment by djsegal** [comment]
Also, the coolest part of the solver is:

+ https://github.com/djsegal/Roots.jl/blob/ad079382f91b62c0db8adf6ac62351b2f2ea3e67/src/bracketing.jl#L798-L837

You might still be able to use that in the final code. I think it should help speed up your code (by tightening up each sub-interval)

**Comment by djsegal** [comment]
I'm cool with whatever. However, this is a little concerning:

> It seems to be a bit faster now than yours but for *the trickier problems requires an adjustment of tolerances*

When I'm running batches of solves, can I really reset tolerances on a per-case basis?

// this might require an auto-tuner step -- which would add more func calls

**Comment by jverzani** [comment]
Fair point. The main issues are functions with way too many zeros (like the tiger tail) and functions with really close by zeros. The first has an easy enough solution -- increase `no_pts`. Though, perhaps it makes sense to do this automatically like in your code. The close by zeros are always a problem. I set the definition of close by to be smaller than (b-a)/100. For a graph, assuming 640x480, this is about 6 pixel separation, which seems small enough that the user should know to make an adjustment (to either more points or to `xatol`.) For the adaptive algorithm setting it here as opposed to, say, (b-a)/1000 makes a big difference. I guess I'd try to tell users that if a graph doesn't show a gap, but you think there may be one, you need to narrow the search space or use more points...

**Comment by djsegal** [comment]
A few questions, can we make a root solver struct that stores:

+ function call count (similar to your `CallableFunction` model)
+ function outputs (where each evaluation gets cached in a dictionary)

And maybe some more stuff. 

------

I just think what's missing at this point is a way to visualize the solver's thought process 

// which would allow users to make their own custom solvers on top of it

**Comment by jverzani** [comment]
I pushed in a simple visualization when `verbose=true` to my `find_zeros` branch. It doesn't do all you ask, as the algorithm doesn't track what happens after `find_zero` is called. (No counting of function calls.) The info about the algorithm's work is in the array `tracks` but it isn't returned by the function, but can be passed in by the caller. With this and the recursing when more zeros are found than expected the performance has dipped, but it is still on par with your version.

Anyway, I'd appreciate your thoughts. Also, I'd like to acknowledge your contributions to the design of this function in the docstring. Are you okay with that?

**Comment by djsegal** [comment]
I'm going to need some time to try to get my root solvers working with your algorithm :/

Definitely running into some cases where I can't find roots or find them too slowly

**Comment by jverzani** [comment]
Can you send examples?

**Comment by jverzani** [comment]
The idea of no_pts being small is the adaptive part of the algorithm. The number is close to what plots.jl uses (used to use?) to make a plot, refining areas where there is more activity. Making it larger isn’t too bad and can catch more roots. I’d be eager to hear if you have better success with a larger value.

**Comment by jverzani** [comment]
Hi @djsegal , I have an alternate PR more in the spirit of this one (https://github.com/JuliaMath/Roots.jl/pull/116). I'd be appreciative if you could try it on your difficult cases and let me know how it performs.

**Comment by djsegal** [comment]
Sorry for going awol. Some of the examples are nested root solves, which I don't know how to easily replicate?

But thanks for all this! Very cool stuff. I just renamed my root solver, and will start experimenting with both. Will close this and leave the rest of the discussion in #116

**Pull request closed without merging**
